import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import TopBar from "@/app/Components/Nav/TopBar";
import Navbar from "@/app/Components/Nav/Navbar";

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair-display',
    weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "NoMeatFactory",
  description: "Generated by Ladan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={playfair.className}
      >
      <TopBar />
      <Navbar />
        {children}
      </body>
    </html>
  );
}
